apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - grafana-instance.yaml
  - rules/openshift-monitoring-access.yaml
  - rules/loki-access.yaml
  - folders/folders.yaml
  - dashboards/openshift/dashboard-openshift-overview.yaml
  - dashboards/gitops/dashboard-argocd.yaml
  - dashboards/identity/dashboard-keycloak-capacity.yaml
  - dashboards/identity/dashboard-keycloak-troubleshooting.yaml
  - dashboards/kubernetes/dashboard-kubernetes-official.yaml
  - dashboards/prometheus/dashboard-prometheus.yaml
  - datasources/zabbix-datasource.yaml
  - datasources/tempo-datasource.yaml
  - datasources/pyroscope-datasource.yaml
  - datasources/loki-datasource.yaml
  - datasources/prometheus-datasource.yaml

labels:
  - pairs:
      app.kubernetes.io/name: grafana
      app.kubernetes.io/instance: grafana-producao
      app.kubernetes.io/component: dashboard
      app.kubernetes.io/part-of: observability
      app.kubernetes.io/managed-by: argocd
      app.kubernetes.io/environment: producao
    includeSelectors: false
