apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: grafana
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    dashboards: grafana
spec:
  config:
    log:
      mode: console
    security:
      admin_user: root
      admin_password: start
    auth:
      disable_login_form: "false"
   route:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "11"
    spec:
      host: grafana-grafana.apps-crc.testing
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
