apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: grafana-operator-og
  namespace: grafana-operator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  targetNamespaces:
    - grafana
