apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: grafana-operator
  namespace: grafana-operator
spec:
  name: grafana-operator
  channel: v5
  source: community-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
