apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: tempo
  namespace: grafana
  annotations:
    argocd.argoproj.io/sync-wave: "23"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana

  valuesFrom:
    - targetPath: secureJsonData.httpHeaderValue1
      valueFrom:
        secretKeyRef:
          name: grafana-tempo-auth
          key: httpHeaderValue1

  datasource:
    uid: tempo
    name: Tempo
    type: tempo
    access: proxy
    url: https://tempo-tempo-monolithic-gateway.tempo.svc.cluster.local:8080/api/traces/v1/dev
    isDefault: false

    jsonData:
      tlsSkipVerify: true
      httpMethod: GET

      httpHeaderName1: Authorization
      httpHeaderName2: X-Scope-OrgID

      nodeGraph:
        enabled: true

      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: "-5m"
        spanEndTimeShift: "5m"
        tags:
          - key: service.name
            value: service_name
        filterByTraceID: true
        filterBySpanID: false

      search:
        hide: false

      traceQuery:
        timeShiftEnabled: true
        spanStartTimeShift: "-5m"
        spanEndTimeShift: "5m"

    secureJsonData:
      httpHeaderValue2: dev